name: coloanex-blockchain-hlf-explorer

networks:
  coloanex_network:
    external: true
  explorer:
    driver: bridge

volumes:
  pgdata:
  walletstore:

services:
  explorerdb:
    image: ghcr.io/hyperledger-labs/explorer-db:latest
    platform: linux/amd64
    container_name: explorerdb.coloanex.com
    hostname: explorerdb.coloanex.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -U hppoc -d fabricexplorer"
      interval: 15s
      timeout: 10s
      retries: 7
      start_period: 30s
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - explorer

  explorer:
    image: ghcr.io/hyperledger-labs/explorer:latest
    platform: linux/amd64
    container_name: explorer.coloanex.com
    hostname: explorer.coloanex.com
    environment:
      - DATABASE_HOST=explorerdb.coloanex.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=info
      - LOG_LEVEL_DB=info
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ../coloanex-blockchain/network/crypto-config:/crypto-config:ro
      - walletstore:/opt/explorer/wallet
    ports:
      - 8080:8080
    depends_on:
      explorerdb:
        condition: service_healthy
    networks:
      - explorer
      - coloanex_network
